Колесникова К.И.
K-ksenia/js_hw3-input-with-select pull request #1
Opened 2019-01-26 14:48 UTC by K-ksenia

2019-01-26 14:58 UTC, xnimorz requested changes

2019-01-26 14:58 UTC, xnimorz commented on script.js
> +                            setContext({outputData: [], selected: event.innerHTML});
зачем полагаться только на html? у тебя же есть вполне нормальный слой бизнес-логики. Лучше разделять слои раз начали

2019-01-26 14:58 UTC, xnimorz commented on script.js
> +const outputList = document.querySelector('.contact-form-select');
Как мне создать на странице два таких селекта?

2019-01-26 14:58 UTC, xnimorz commented on script.js
> +                        if (event.length >= 2) {
здесь без погружения в код нельзя разобрать, что предыдущий разработчик имел в виду.  
Код стоит писать таким, чтобы он был понятен разработчику конечному

2019-01-26 14:58 UTC, xnimorz commented on script.js
> +                                        throw new Error('Error while fetching');
описывая такую ошибку ты никогда потом не сможешь понять — что же в действительности было не так

2019-01-26 14:58 UTC, xnimorz commented on script.js
> +                                        throw new Error('Error while fetching');
К слову сказать, сейчас я могу в селект вбивать пробелы и поход в апи выдаст 400 ошибку.

2019-01-26 14:58 UTC, xnimorz commented on script.js
> +    selectMachine.transition('CHOOSE', e.target)
В фронтенд разработке важно держать сайт доступным для пользователей с разными компьюттерами в разных конфигурациях. 
В том числе хорошо, если пользователь сможет взаимодействовать с сайтом, используя только клавиатуру. Сейчас он этого сделать не сможет.

2019-01-26 16:28 UTC, K-ksenia commented on script.js
> +const outputList = document.querySelector('.contact-form-select');
Имеешь в виду, что если у меня на странице будет несколько элементов с селектором .contact-form-select?

2019-01-26 16:48 UTC, K-ksenia commented on script.js
> +                                        throw new Error('Error while fetching');
Потому что если fetch провалится, он даже не зайдет внутрь, а сразу прыгнет на catch?

2019-01-26 16:48 UTC, K-ksenia commented on script.js
> +                                        throw new Error('Error while fetching');
Или сам текст ошибки некорректный и лучше выводить хотя бы этот самый response.status

2019-01-26 19:11 UTC, xnimorz commented on script.js
> +const outputList = document.querySelector('.contact-form-select');
Да, сейчас ты физически не сможешь заинициализровать несколько элементов т.е. в идеале сделать механизм инита

2019-01-26 19:11 UTC, xnimorz commented on script.js
> +                                        throw new Error('Error while fetching');
обычно выкидывают наружу статус код и тело (хотя бы)

2019-02-01 08:31 UTC, xnimorz approved these changes
Посмотрел, ошибки учтены

2019-09-03 11:45 UTC, closed without merging